###

POST http://localhost:3000/graphics-cards
Content-Type: application/json

{
    "name": "Geforce GTX1050ti",
    "brand": "Gigabyte",
    "price": 835,
    "image": "https://images-na.ssl-images-amazon.com/images/I/81VBPk5pnLL._AC_SL1500_.jpg",
    "memory": "16Gb",
    "frecuence": "8800mhz"
}
